"use client"
import { useState } from "react";
import { Share } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/sonner";
import { UpdateCartContext } from "./_context/UpdateCart";
import Footer from "./_components/Footer";

const share = Share({ 
  subsets: ["latin"],
  weight: '700'
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [updateCart, setUpdateCart] = useState(false);
  
  return (
    <html lang="es">
      <body className={share.className}>
        <UpdateCartContext.Provider value={[updateCart,setUpdateCart]}>
          <Header />
          {children}
          <Toaster />
        </UpdateCartContext.Provider>
        <Footer className="p-5 md:p-15 px-16" />
      </body>
    </html>
  );
}
